In [1]:
import torch

In [2]:
torch.__version__

'2.0.1+cu117'

# Playing with tensors

In [3]:
# [height, width, color_channels]
random_image_size_tensor = torch.rand(size=(8, 8, 3))
random_image_size_tensor

tensor([[[0.1289, 0.7801, 0.6462],
         [0.5257, 0.5695, 0.0443],
         [0.1632, 0.2769, 0.7638],
         [0.8069, 0.9988, 0.7421],
         [0.3235, 0.1107, 0.3117],
         [0.8992, 0.9836, 0.0342],
         [0.5950, 0.5520, 0.1955],
         [0.8193, 0.0214, 0.1036]],

        [[0.0900, 0.1600, 0.5997],
         [0.4678, 0.2563, 0.6731],
         [0.4661, 0.7243, 0.9126],
         [0.9681, 0.6846, 0.9025],
         [0.1539, 0.3601, 0.4460],
         [0.3041, 0.2347, 0.8819],
         [0.4037, 0.0050, 0.5979],
         [0.0563, 0.8703, 0.0464]],

        [[0.7360, 0.2918, 0.0932],
         [0.8772, 0.4969, 0.8121],
         [0.0866, 0.6582, 0.0730],
         [0.5740, 0.4962, 0.2589],
         [0.6324, 0.0550, 0.6046],
         [0.6300, 0.3304, 0.7729],
         [0.8363, 0.0124, 0.4056],
         [0.4781, 0.0029, 0.6973]],

        [[0.5788, 0.4318, 0.1678],
         [0.5371, 0.3060, 0.3155],
         [0.9157, 0.5444, 0.8874],
         [0.3908, 0.6539, 0.3401],
         [0.46

In [6]:
X = torch.arange(start=-10, end=10, step=0.4).float()
X, X.dtype

(tensor([-1.0000e+01, -9.6000e+00, -9.2000e+00, -8.8000e+00, -8.4000e+00,
         -8.0000e+00, -7.6000e+00, -7.2000e+00, -6.8000e+00, -6.4000e+00,
         -6.0000e+00, -5.6000e+00, -5.2000e+00, -4.8000e+00, -4.4000e+00,
         -4.0000e+00, -3.6000e+00, -3.2000e+00, -2.8000e+00, -2.4000e+00,
         -2.0000e+00, -1.6000e+00, -1.2000e+00, -8.0000e-01, -4.0000e-01,
         -5.9605e-09,  4.0000e-01,  8.0000e-01,  1.2000e+00,  1.6000e+00,
          2.0000e+00,  2.4000e+00,  2.8000e+00,  3.2000e+00,  3.6000e+00,
          4.0000e+00,  4.4000e+00,  4.8000e+00,  5.2000e+00,  5.6000e+00,
          6.0000e+00,  6.4000e+00,  6.8000e+00,  7.2000e+00,  7.6000e+00,
          8.0000e+00,  8.4000e+00,  8.8000e+00,  9.2000e+00,  9.6000e+00]),
 torch.float32)

In [7]:
print("Minimum:", X.min())
print("Maximum:", X.max())
print("Mean:", X.mean())
print("Sum:", X.sum())
print(f"Index where max value occurs: {X.argmax()}")
print(f"Index where min value occurs: {X.argmin()}")

Minimum: tensor(-10.)
Maximum: tensor(9.6000)
Mean: tensor(-0.2000)
Sum: tensor(-10.0000)
Index where max value occurs: 49
Index where min value occurs: 0


# Dimensions!

In [14]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [16]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [19]:
# Add an extra dimension
x_reshaped = x.reshape(1, 1, 7)
x_reshaped, x_reshaped.shape

(tensor([[[1., 2., 3., 4., 5., 6., 7.]]]), torch.Size([1, 1, 7]))

In [22]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [23]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[[1., 2., 3., 4., 5., 6., 7.]]])
Previous shape: torch.Size([1, 1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [30]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])

New tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])
New shape: torch.Size([7, 1])


In [31]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [32]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [33]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [34]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8927, 0.4413, 0.6946, 0.2083],
        [0.8233, 0.2819, 0.4163, 0.2326],
        [0.6612, 0.7536, 0.5252, 0.2311]])

Tensor B:
tensor([[0.8166, 0.1093, 0.7743, 0.0584],
        [0.6976, 0.8706, 0.2267, 0.2702],
        [0.5450, 0.9603, 0.6979, 0.9904]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [35]:
# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])